In [4]:
import pandas as pd

column_names = [
    'SepalLengthCm',
    'SepalWidthCm',
    'PetalLengthCm',
    'PetalWidthCm',
    'Species'
]

df = pd.read_csv(
    "../datasets/Iris/Iris.csv",
    header=None,
    names=column_names
)

df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
setosa = df[df['Species'] == 'Iris-setosa']
virginica = df[df['Species'] == 'Iris-virginica']

setosa.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
merged_data = pd.concat([setosa, virginica])

merged_data.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
sorted_data = df.sort_values(by='PetalLengthCm', ascending=False)

sorted_data.head()

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
118            7.7           2.6            6.9           2.3  Iris-virginica
122            7.7           2.8            6.7           2.0  Iris-virginica
117            7.7           3.8            6.7           2.2  Iris-virginica
105            7.6           3.0            6.6           2.1  Iris-virginica
131            7.9           3.8            6.4           2.0  Iris-virginica

In [8]:
transposed_data = df.head().T

transposed_data

                         0            1            2            3            4
SepalLengthCm          5.1          4.9          4.7          4.6          5.0
SepalWidthCm           3.5          3.0          3.2          3.1          3.6
PetalLengthCm          1.4          1.4          1.3          1.5          1.4
PetalWidthCm           0.2          0.2          0.2          0.2          0.2
Species        Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa

In [9]:
melted_data = pd.melt(
    df,
    id_vars=['Species'],
    value_vars=['PetalLengthCm']
)

melted_data.head()

       Species       variable  value
0  Iris-setosa  PetalLengthCm    1.4
1  Iris-setosa  PetalLengthCm    1.4
2  Iris-setosa  PetalLengthCm    1.3
3  Iris-setosa  PetalLengthCm    1.5
4  Iris-setosa  PetalLengthCm    1.4

In [10]:
pivot_data = df.pivot_table(
    values='PetalLengthCm',
    index='Species',
    aggfunc='mean'
)

pivot_data

                 PetalLengthCm
Species
Iris-setosa              1.464
Iris-versicolor          4.260
Iris-virginica           5.552