In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("../datasets/dataset_Facebook.csv", sep=";")
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [5]:
photo_posts = df[df['Type'] == 'Photo']
status_posts = df[df['Type'] == 'Status']

photo_posts.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279

In [6]:
merged_data = pd.concat([photo_posts, status_posts])

merged_data.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279

In [7]:
sorted_data = df.sort_values(by='Page total likes', ascending=False)

sorted_data[['Type', 'Page total likes']].head()

      Type  Page total likes
0    Photo            139441
8   Status            139441
1   Status            139441
12   Photo            139441
11   Photo            139441

In [8]:
transposed_data = df.head().T

transposed_data

,0,1,2,3,4
Page total likes,139441,139441,139441,139441,139441
Type,Photo,Status,Photo,Photo,Photo
Category,2,2,3,2,2
Post Month,12,12,12,12,12
Post Weekday,4,3,3,2,2
Post Hour,3,10,3,10,3
Paid,0.0,0.0,0.0,1.0,0.0
Lifetime Post Total Reach,2752,10460,2413,50128,7244
Lifetime Post Total Impressions,5091,19057,4373,87991,13594
Lifetime Engaged Users,178,1457,177,2211,671
Lifetime Post Consumers,109,1361,113,790,410
Lifetime Post Consumptions,159,1674,154,1119,580
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396
comment,4,5,0,58,19
like,79.0,130.0,66.0,1572.0,325.0
share,17.0,29.0,14.0,147.0,49.0
Total Interactions,100,164,80,1777,393

In [9]:
melted_data = pd.melt(
    df,
    id_vars=['Type'],
    value_vars=['Page total likes']
)

melted_data.head()

     Type          variable   value
0   Photo  Page total likes  139441
1  Status  Page total likes  139441
2   Photo  Page total likes  139441
3   Photo  Page total likes  139441
4   Photo  Page total likes  139441

In [10]:
pivot_data = df.pivot_table(
    values='Page total likes',
    index='Type',
    aggfunc='mean'
)

pivot_data

        Page total likes
Type
Link       116363.181818
Photo      122354.171362
Status     132647.044444
Video      135014.857143